vim.cmd [[colorscheme retrobox]]
vim.o.number = true
vim.o.relativenumber = true
vim.o.colorcolumn = "80,120"
vim.o.expandtab = true
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.b.autoformat = false
vim.o.listchars = "tab:<->,trail:-,nbsp:+"
